---
swagger: "2.0"
info:
  title: "Food Delivery Service API"
  description: "This is the MVP application `documentation` from the [Food Delivery Service](https://github.com/EuCarlos/food-delivery-service-react-rails) project created with Ruby on Rails."
  version: "1.0.0"
  contact:
    email: "carlosalves369m@hotmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:3000"
basePath: "/api"
tags:
- name: "category"
  description: "All categories"
- name: "restaurant"
  description: "All restaurants"
- name: "order"
  description: "All orders"
- name: "cities"
  description: "All available cities"
schemes:
- "https"
- "http"
paths:
  /categories:
    get:
      tags:
      - "category"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Category not found"
  /restaurants:
    get:
      tags:
      - "restaurant"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Category not found"
  /restaurant/{id}:
    get:
      tags:
      - "restaurant"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of restaurant to restaurants list"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Restaurant not found"
  /orders:
    post:
      tags:
      - "order"
      post:
      summary: "Place an order for a restaurant"
      description: ""
      operationId: "placeOrder"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "order made to purchase"
        required: true
        schema:
          $ref: "#/definitions/Order"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Order not found"
  /order/{id}:
    get:
      tags:
      - "order"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of order to orders list"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Order not found"
  /available_cities:
    get:
      tags:
      - "cities"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "City not found"
definitions:
  Products_attributes:
    type: "object"
    properties:
      quantity:
        type: "integer"
        example: 2
      product_id:
        type: "integer"
        example: 6
  Order:
    type: "object"
    properties:
      order:
        type: "object"
        formart: "int64"
        properties:
          restaurant_id:
            type: "integer"
            example: 9
          name:
            type: "string"
            example: "Carlos Alves"
          phone_number:
            type: "string"
            example: "(22) 91234-5678"
          city:
            type: "string"
            example: "Curitiba"
          street:
            type: "string"
            example: "São João"
          neighborhood:
            type: "string"
            example: "Tingui"
          number:
            type: "string"
            example: "115"
          complement:
            type: "string"
            example: "apartamento 4"
          order_products_attributes:
            type: "array"
            items: 
              $ref: "#/definitions/Products_attributes"