---
swagger: "2.0"
info:
  title: "Food Delivery Service API"
  description: "This is the MVP application `documentation` from the [Food Delivery Service](https://github.com/EuCarlos/food-delivery-service-react-rails) project created with Ruby on Rails."
  version: "1.0.0"
  contact:
    email: "carlosalves369m@hotmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:3000"
basePath: "/api"
tags:
- name: "category"
  description: "All categories"
- name: "restaurant"
  description: "All restaurants"
- name: "order"
  description: "All orders"
- name: "cities"
  description: "All available cities"
schemes:
- "https"
- "http"
paths:
  /categories:
    get:
      tags:
      - "category"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: array
            items:
              $ref: "#/definitions/Categories"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Category not found"
  /restaurants:
    get:
      tags:
      - "restaurant"
      parameters:
        - in: query
          name: q
          description: "filter all restaurants by query"
          require: false
          schema:
            type: string
            example: "Los Sombreros"
        - in: query
          name: city
          description: "filter all restaurants by city"
          require: false
          schema:
            type: string
            example: "São Paulo"
        - in: query
          name: category
          description: "filter all restaurants by category"
          require: false
          schema:
            type: string
            example: "mexicana"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: array
            items:
              $ref: "#/definitions/Restaurants"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Category not found"
  /restaurant/{id}:
    get:
      tags:
      - "restaurant"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of restaurant to restaurants list"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Restaurants"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Restaurant not found"
  /orders:
    post:
      tags:
      - "order"
      post:
      summary: "Place an order for a restaurant"
      description: ""
      operationId: "placeOrder"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "order made to purchase"
        required: true
        schema:
          $ref: "#/definitions/Orders"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Orders"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Order not found"
  /order/{id}:
    get:
      tags:
      - "order"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of order to orders list"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Order"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Order not found"
  /available_cities:
    get:
      tags:
      - "cities"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/AvailableCities"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "City not found"
definitions:
  Categories:
    type: object
    properties:
      id:
        type: number
        example: 2
      title:
        type: string
        example: "italiana"
      image_url:
        type: string
        example: "http://carlosalves.vercel.app/rails/active_storage/blobs/redirect/.../italian.jpeg"
  Restaurants:
    type: object
    properties:
      id:
        type: number
        example: 1
      name:
        type: string
        example: "Los Sombreros"
      description:
        type: string
        example: "Nossa missão tem sido ajudar as pessoas a alcançar seus objetivos de saúde e bem-estar. Embora tenhamos mudado ao longo dos anos, nossos valores permaneceram os mesmos."
      delivery_tax:
        type: number
        example: 5.5
      city:
        type: string
        example: "São Paulo"
      street:
        type: string
        example: "Bela terra"
      neighborhood:
        type: string
        example: "Mercês"
      number:
        type: string
        example: "1393"
      complement:
        type: string
        example: null
      image_url:
        type: array
        items:
          example: "http://carlosalves.vercel.app/rails/active_storage/blobs/redirect/.../1.jpg"
      category_title:
        type: string
        example: "mexicana"
      product_categories:
        type: array
        items:
          type: object
          properties:
            id:
              type: number
              example: 1
            title:
              type: string
              example: "Pratos Mexicanos"
            products:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: number
                    example: 1
                  name:
                    type: string
                    example: "Nacho Guacamole"
                  description:
                    type: string
                    example: "Tortilhas com Guacamole"
                  price:
                    type: number
                    example: 19.27
                  image_url:
                    type: string
                    example: "http://carlosalves.vercel.app/rails/active_storage/blobs/redirect/.../nachosg.jpg"
        
        
  Products_attributes:
    type: object
    properties:
      quantity:
        type: integer
        example: 2
      product_id:
        type: integer
        example: 6
  Orders:
    type: object
    properties:
      order:
        type: object
        formart: "int64"
        properties:
          restaurant_id:
            type: integer
            example: 9
          name:
            type: string
            example: "Carlos Alves"
          phone_number:
            type: string
            example: "(22) 91234-5678"
          city:
            type: string
            example: "Curitiba"
          street:
            type: string
            example: "São João"
          neighborhood:
            type: string
            example: "Tingui"
          number:
            type: string
            example: "115"
          complement:
            type: string
            example: "apartamento 4"
          order_products_attributes:
            type: array
            items: 
              $ref: "#/definitions/Products_attributes"
  Order:
    type: object
    properties:
      id:
        type: number
        example: 1
      restaurant_id:
        type: number
        example: 3
      total_value:
        type: number
        example: 195.5
      status:
        type: string
        example: "waiting"
      city:
        type: string
        example: "Curitiba"
      street:
        type: string
        example: "São João"
      neighborhood:
        type: string
        example: "Tingui"
      number:
        type: string
        example: "115"
      complement:
        type: string
        example: "BL A AP 4"
  AvailableCities:
    type: object
    properties:
      available_cities:
        type: array
        items: 
          example: ["São Paulos", "Curitiba", "Maceio"]